### ISSUE TITLE
Improve material handling if imported material already has UVID

### ISSUE THREAD

**Issue by janvonrickenbach** [ansys/pyacp#342]
- The current workflow does not work when a material in the inital cdb file already has a vuid. This material ends up in the rst file with its vuid, but is not written to the MatML xml file. Proposed new workflow:
   - Import material as locked and generate vuid if needed. Rename should be possible, because the imported material does not have a real name (just "1" for example)
    - Write material to MatML xml file (should happen automatically)
```[tasklist]
### Tasks
- [x] Run ARM tests
- [x] Merge PR of ACP kernel
- [x] Update CDB file in ansys example-data
```
