### ISSUE TITLE
Polish pyacp module

### ISSUE THREAD

**Issue by roosre** [ansys/pyacp#670]
- [x] Elemental and NodalData -> put into separate NameSpace  #686 
- [x] Class ACP -> rename to ACPInstance #675 
- [x] TriangleMesh -> move to separate namespace #686  
- [x] VectorData -> move to separate namespace #686  
- [x] ScalarData -> move to separate namespace #686 
- [x] example_helpers -> move to separate namesapce  #675 
- [x] #693
- [x] rename `image_name_pyacp` to `image_name_acp`  #675 
- [x] rename PORT_PYACP to PORT_ACP  #675 
- [x] rename `import_acp_solid_mesh` helper? Could it be used also for shells?

**Comment by greschd** [comment]
@roosre agreed overall, just some minor points:

> Class ACP -> rename to ACPServer or ACPInstance

That _was_ actually called `ACPServer` at some point (or `ACPInstance`, I don't remember), before we merged the "client" and "server" functionality into one. I'm now a bit on the fence whether we should rename it back.

> Enums -> Move to separate namespace?

For this one I think I'll want to create a branch with the change and see how it changes the example code (when enums are used, not strings). I think it's not entirely clear whether to put all enums in one namespace, or group them by usage (e.g. all solid model - related enums). The former is _somewhat_ odd, but grouping by usage will be difficult to remember especially since the main types are all top-level.

>  example_helpers -> move to separate namesapce

This _is_ a separate namespace already.

**Comment by roosre** [comment]
@greschd , thanks for the response.

Enum: I wanted to remove this point from the list and keep it as it is. Sorry about that.

ACP -> ACPClient / ACP Instance: thanks for the info. Good to know and so let's discuss it next week.

**Comment by greschd** [comment]
@roosre is this one and #637 done, or is something left to do from your point of view?
